apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-standard-claim-30gi
spec:
  storageClassName: {{ .Release.Name }}-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi