apiVersion: v1
kind: Service
metadata:
  name: {{ include "awslambda.fullname" . }}
  labels:
    {{- include "awslambda.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalName }}
  selector:
    {{- include "awslambda.selectorLabels" . | nindent 4 }}
